INSERT INTO boards (author, content, title) VALUES ('userid1','content1','title1');
INSERT INTO boards (author, content, title) VALUES ('userid2','content2','title2');
INSERT INTO boards (author, content, title) VALUES ('userid3','content3','title3');
INSERT INTO boards (author, content, title) VALUES ('userid4','content4','title4');
INSERT INTO boards (author, content, title) VALUES ('userid5','content5','title5');
INSERT INTO boards (author, content, title) VALUES ('userid6','content6','title6');
INSERT INTO boards (author, content, title) VALUES ('userid7','content7','title7');
INSERT INTO boards (author, content, title) VALUES ('userid8','content8','title8');
INSERT INTO boards (author, content, title) VALUES ('userid9','content9','title9');
